server:
  port: 8081  # 端口

spring: # 数据源配置
  thymeleaf:
    prefix: classpath:/templates/travel/
    suffix: .html
    cache: false
    mode: HTML5

  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/travel_data?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 1348432081@qq.com
    password: pugegbgvsjnqieca
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true



mybatis:
   type-aliases-package: com.gradution.chao.graductiondesign.pojo # 实体类位置

